// Command bench measures how many operations per second one BalanceDB cell
// sustains end to end: registrations committed by concurrent inserters AND
// decided by the single elected leader.
//
// It runs directly against Postgres through the same insertion core the HTTP api
// uses (internal/ledger) and the same processor the `processor` role runs, so the
// numbers are the cell's ceiling with no HTTP in the way (spec §14: "the cell's
// database bounds throughput"). Add an api node in front with `make loadgen` when
// you want the HTTP-inclusive figure.
//
// For each worker count in -workers it runs a warmup, waits for the leader to drain
// the backlog, then measures a fixed insertion window with closed-loop inserters
// (each worker: BEGIN → Insert → COMMIT, repeat), stops, and waits for the leader to
// drain again. It reports both sides of the system per level:
//
//   - insertion: ops/s and registrations/s committed, client-observed commit latency;
//   - the leader: ops/s decided while inserts were running, backlog at the end of the
//     window, time to drain it, and the sustained rate = ops / (window + drain) —
//     the honest "what the cell can hold" number when the backlog grows;
//   - end-to-end latency (registered_at → confirmed_at, both DB clock) percentiles;
//   - loop utilization ρ (spec §13), the capacity signal: 0.4 at 800 ops/s means the
//     leader has room for ~2,000 ops/s before the backlog starts to grow.
//
// Amounts are positive against unbounded accounts, so every operation is accepted —
// the point is throughput, not validation. It is a developer tool, not part of any
// deployed binary; it never touches a schema you did not name unless it created it.
package main

import (
	"context"
	cryptorand "crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"math"
	"math/rand"
	"os"
	"os/signal"
	"sort"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"syscall"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/magnomp/balancedb/internal/db"
	"github.com/magnomp/balancedb/internal/lease"
	"github.com/magnomp/balancedb/internal/ledger"
	"github.com/magnomp/balancedb/internal/migrate"
	"github.com/magnomp/balancedb/internal/obs"
	"github.com/magnomp/balancedb/internal/processor"
)

// SQL for the benchmark's own observations, kept as consts beside their single call
// site (plan §0), unqualified — search_path owns the schema.
const (
	selectConfig    = `SELECT lease_ttl_ms, loop_interval_ms, batch_size, max_group_size FROM config`
	updateBatchSize = `UPDATE config SET batch_size = $1`
	updateLoopMs    = `UPDATE config SET loop_interval_ms = $1`
	updateMaxGroup  = `UPDATE config SET max_group_size = $1`
	selectVersion   = `SELECT current_setting('server_version')`

	// The pending count uses the partial work index (idx_ops_work), the same query
	// the processor's own queue-depth gauge runs: cheap while the backlog is small,
	// proportional to the backlog otherwise.
	selectPending = `SELECT count(*) FROM operations WHERE status = 'PENDING'`
	selectMaxID   = `SELECT COALESCE(max(id), 0) FROM operations`

	// End-to-end latency for the operations registered in one measured window:
	// registered_at (insert transaction start) to confirmed_at (the deciding batch
	// transaction start), both taken from the DB clock, so no process clock is mixed
	// in. It slightly undercounts the deciding batch's own commit time.
	selectLatency = `SELECT count(*) FILTER (WHERE confirmed_at IS NOT NULL),
       percentile_cont(0.5)  WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (confirmed_at - registered_at))::float8),
       percentile_cont(0.95) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (confirmed_at - registered_at))::float8),
       percentile_cont(0.99) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (confirmed_at - registered_at))::float8),
       max(EXTRACT(EPOCH FROM (confirmed_at - registered_at))::float8)
  FROM operations WHERE id > $1 AND id <= $2`
	selectStatuses = `SELECT status, count(*) FROM operations WHERE id > $1 AND id <= $2 GROUP BY status ORDER BY status`
)

// options is the parsed command line.
type options struct {
	dbURL        string
	schema       string
	generated    bool // schema was generated by this run (and is dropped unless keep)
	keep         bool
	workers      []int
	warmup       time.Duration
	duration     time.Duration
	drainTimeout time.Duration
	accounts     int
	groupSize    int
	backdateDays int
	batchSize    int
	loopMs       int
	external     bool
	jsonPath     string
	owner        int64
}

// levelResult is one row of the report: everything measured at one worker count.
type levelResult struct {
	Workers int `json:"workers"`

	// Insertion side (measured window only).
	Ops           int64   `json:"ops"`
	Registrations int64   `json:"registrations"`
	InsertErrors  int64   `json:"insert_errors"`
	InsertOpsPerS float64 `json:"insert_ops_per_s"`
	InsertRegPerS float64 `json:"insert_registrations_per_s"`
	InsertP50Ms   float64 `json:"insert_p50_ms"`
	InsertP95Ms   float64 `json:"insert_p95_ms"`
	InsertP99Ms   float64 `json:"insert_p99_ms"`

	// Leader side.
	LeaderOpsPerS    float64  `json:"leader_ops_per_s"` // decided while inserts ran
	BacklogAtEnd     int64    `json:"backlog_at_end"`
	DrainSeconds     float64  `json:"drain_seconds"`
	Drained          bool     `json:"drained"`
	SustainedOpsPerS float64  `json:"sustained_ops_per_s"` // ops / (window + drain)
	Rho              *float64 `json:"rho,omitempty"`       // nil when the leader is external

	// End-to-end (DB clock).
	E2EP50Ms float64 `json:"e2e_p50_ms"`
	E2EP95Ms float64 `json:"e2e_p95_ms"`
	E2EP99Ms float64 `json:"e2e_p99_ms"`
	E2EMaxMs float64 `json:"e2e_max_ms"`

	Statuses map[string]int64 `json:"statuses"`
}

// report is the JSON document written by -json: run metadata plus one levelResult
// per worker count, so a CI job or a notebook can track the numbers over time.
type report struct {
	StartedAt       time.Time     `json:"started_at"`
	PostgresVersion string        `json:"postgres_version"`
	Schema          string        `json:"schema"`
	GroupSize       int           `json:"group_size"`
	Accounts        int           `json:"accounts"`
	BackdateDays    int           `json:"backdate_days"`
	BatchSize       int           `json:"batch_size"`
	LoopIntervalMs  int           `json:"loop_interval_ms"`
	LeaseTTLMs      int           `json:"lease_ttl_ms"`
	WarmupSeconds   float64       `json:"warmup_seconds"`
	WindowSeconds   float64       `json:"window_seconds"`
	Levels          []levelResult `json:"levels"`
}

func main() {
	opts, err := parseFlags()
	if err != nil {
		fmt.Fprintln(os.Stderr, "bench:", err)
		os.Exit(2)
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	if err := run(ctx, opts); err != nil {
		if errors.Is(err, context.Canceled) {
			fmt.Fprintln(os.Stderr, "bench: interrupted")
			os.Exit(130)
		}
		fmt.Fprintln(os.Stderr, "bench:", err)
		os.Exit(1)
	}
}

func parseFlags() (options, error) {
	var o options
	var workers string
	flag.StringVar(&o.dbURL, "db", "", "database URL (default: $TEST_DATABASE_URL, then $BALANCEDB_DATABASE_URL)")
	flag.StringVar(&o.schema, "schema", "", "schema to benchmark in; migrated if needed, never dropped (default: a fresh bench_<hex> schema, dropped on exit)")
	flag.BoolVar(&o.keep, "keep", false, "keep a generated schema after the run instead of dropping it")
	flag.StringVar(&workers, "workers", "1,4,16,64", "comma-separated concurrent inserter counts to sweep, one measured level each")
	flag.DurationVar(&o.warmup, "warmup", 3*time.Second, "unmeasured warmup insertion per level")
	flag.DurationVar(&o.duration, "duration", 15*time.Second, "measured insertion window per level")
	flag.DurationVar(&o.drainTimeout, "drain-timeout", 2*time.Minute, "how long to wait for the leader to drain the backlog after a level")
	flag.IntVar(&o.accounts, "accounts", 1000, "distinct accounts (one owner) to spread operations over")
	flag.IntVar(&o.groupSize, "group-size", 1, "operations per registration: 1 = singles, >1 = atomic groups")
	flag.IntVar(&o.backdateDays, "backdate-days", 0, "spread effective_at uniformly over the last N days (0 = now; >0 exercises the snapshot cascade)")
	flag.IntVar(&o.batchSize, "batch-size", 0, "override config.batch_size for this run (0 = keep the cell's value)")
	flag.IntVar(&o.loopMs, "loop-interval-ms", 0, "override config.loop_interval_ms for this run (0 = keep the cell's value)")
	flag.BoolVar(&o.external, "external-processor", false, "do not run a leader in-process: a processor is already running against -schema (rho is then not available)")
	flag.StringVar(&o.jsonPath, "json", "", "also write the results as JSON to this file")
	flag.Int64Var(&o.owner, "owner", 1, "owner id the accounts belong to")
	flag.Parse()

	if o.dbURL == "" {
		o.dbURL = os.Getenv("TEST_DATABASE_URL")
	}
	if o.dbURL == "" {
		o.dbURL = os.Getenv("BALANCEDB_DATABASE_URL")
	}
	if o.dbURL == "" {
		return o, errors.New("-db is required (or set TEST_DATABASE_URL / BALANCEDB_DATABASE_URL)")
	}
	for _, part := range strings.Split(workers, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		n, err := strconv.Atoi(part)
		if err != nil || n < 1 {
			return o, fmt.Errorf("-workers: %q is not a positive integer", part)
		}
		o.workers = append(o.workers, n)
	}
	if len(o.workers) == 0 {
		return o, errors.New("-workers must list at least one level")
	}
	if o.accounts < 1 || o.groupSize < 1 || o.backdateDays < 0 || o.batchSize < 0 || o.loopMs < 0 || o.owner < 1 {
		return o, errors.New("-accounts, -group-size and -owner must be >= 1; -backdate-days, -batch-size and -loop-interval-ms must be >= 0")
	}
	if o.duration <= 0 {
		return o, errors.New("-duration must be positive")
	}
	if o.schema == "" {
		var b [4]byte
		if _, err := cryptorand.Read(b[:]); err != nil {
			return o, fmt.Errorf("generate schema name: %w", err)
		}
		o.schema = "bench_" + hex.EncodeToString(b[:])
		o.generated = true
	}
	if o.external && o.generated {
		return o, errors.New("-external-processor needs -schema: the running processor must be bound to the same schema")
	}
	return o, nil
}

func run(ctx context.Context, o options) error {
	started := time.Now()
	fmt.Fprintf(os.Stderr, "bench: migrating schema %s\n", o.schema)
	if _, err := migrate.Run(ctx, o.dbURL, o.schema); err != nil {
		return fmt.Errorf("migrate: %w", err)
	}
	if o.generated && !o.keep {
		defer func() {
			// Fresh context: the run's ctx may already be cancelled (Ctrl-C).
			dropCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			if err := dropSchema(dropCtx, o.dbURL, o.schema); err != nil {
				fmt.Fprintf(os.Stderr, "bench: drop schema %s: %v\n", o.schema, err)
			}
		}()
	}

	// The client pool is what the inserters use; two spare connections serve the
	// once-per-second sampler and the end-of-level queries without queueing behind
	// a worker.
	maxWorkers := 0
	for _, w := range o.workers {
		maxWorkers = max(maxWorkers, w)
	}
	pool, err := db.Connect(ctx, o.dbURL, o.schema, int32(maxWorkers+2))
	if err != nil {
		return err
	}
	defer pool.Close()

	rep := report{
		StartedAt:     started,
		Schema:        o.schema,
		GroupSize:     o.groupSize,
		Accounts:      o.accounts,
		BackdateDays:  o.backdateDays,
		WarmupSeconds: o.warmup.Seconds(),
		WindowSeconds: o.duration.Seconds(),
	}
	if err := pool.QueryRow(ctx, selectVersion).Scan(&rep.PostgresVersion); err != nil {
		return fmt.Errorf("read server version: %w", err)
	}
	if err := applyConfig(ctx, pool, o, &rep); err != nil {
		return err
	}
	if err := createAccounts(ctx, pool, o); err != nil {
		return err
	}

	// The leader. In-process by default, wired exactly as cmd/balancedb wires the
	// processor role (own pool, lease, metrics sink) so ρ can be read from the
	// registry; -external-processor trusts a processor that is already running.
	var metrics *obs.Metrics
	if !o.external {
		procPool, err := db.Connect(ctx, o.dbURL, o.schema, 4)
		if err != nil {
			return fmt.Errorf("processor pool: %w", err)
		}
		defer procPool.Close()
		l, err := lease.New(procPool)
		if err != nil {
			return fmt.Errorf("processor lease: %w", err)
		}
		metrics = obs.NewMetrics(procPool)
		logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelWarn}))
		proc := processor.New(procPool, l, logger)
		proc.SetMetrics(metrics)

		procCtx, cancel := context.WithCancel(ctx)
		done := make(chan struct{})
		go func() {
			defer close(done)
			if err := proc.Run(procCtx); err != nil {
				logger.Error("processor exited", "err", err)
			}
		}()
		defer func() { cancel(); <-done }()

		if err := waitForLeader(ctx, proc, time.Duration(rep.LeaseTTLMs)*time.Millisecond+10*time.Second); err != nil {
			return err
		}
	}

	printHeader(o, rep)
	gen := newWorkload(o)
	for _, w := range o.workers {
		res, err := runLevel(ctx, pool, metrics, o, gen, w)
		if err != nil {
			return err
		}
		rep.Levels = append(rep.Levels, res)
		printRow(res)
	}
	printFooter(rep)

	if o.jsonPath != "" {
		if err := writeJSON(o.jsonPath, rep); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "bench: wrote %s\n", o.jsonPath)
	}
	if o.generated && o.keep {
		fmt.Fprintf(os.Stderr, "bench: kept schema %s\n", o.schema)
	}
	return nil
}

// applyConfig applies the -batch-size / -loop-interval-ms overrides, raises
// max_group_size when the requested group size would be rejected, and records the
// effective config row in the report.
func applyConfig(ctx context.Context, pool *pgxpool.Pool, o options, rep *report) error {
	if o.batchSize > 0 {
		if _, err := pool.Exec(ctx, updateBatchSize, o.batchSize); err != nil {
			return fmt.Errorf("set batch_size: %w", err)
		}
	}
	if o.loopMs > 0 {
		if _, err := pool.Exec(ctx, updateLoopMs, o.loopMs); err != nil {
			return fmt.Errorf("set loop_interval_ms: %w", err)
		}
	}
	var maxGroup int
	if err := pool.QueryRow(ctx, selectConfig).Scan(&rep.LeaseTTLMs, &rep.LoopIntervalMs, &rep.BatchSize, &maxGroup); err != nil {
		return fmt.Errorf("read config: %w", err)
	}
	if o.groupSize > maxGroup {
		fmt.Fprintf(os.Stderr, "bench: raising config.max_group_size from %d to %d for -group-size\n", maxGroup, o.groupSize)
		if _, err := pool.Exec(ctx, updateMaxGroup, o.groupSize); err != nil {
			return fmt.Errorf("set max_group_size: %w", err)
		}
	}
	return nil
}

// createAccounts pre-creates every account (unbounded limits) so first-touch
// creation never lands inside a measured window. An existing account is fine: a
// named schema may be reused across runs.
func createAccounts(ctx context.Context, pool *pgxpool.Pool, o options) error {
	fmt.Fprintf(os.Stderr, "bench: ensuring %d accounts\n", o.accounts)
	for i := 0; i < o.accounts; i++ {
		_, err := ledger.CreateAccount(ctx, pool, o.owner, accountName(i), ledger.Limits{})
		if err != nil && !errors.Is(err, ledger.ErrAccountExists) {
			return fmt.Errorf("create account %s: %w", accountName(i), err)
		}
	}
	return nil
}

func accountName(i int) string { return "bench-" + strconv.Itoa(i) }

// waitForLeader blocks until the in-process processor holds the lease. A named
// schema reused after a killed run may carry a stale lease, so the bound is one
// lease TTL plus slack.
func waitForLeader(ctx context.Context, proc *processor.Processor, within time.Duration) error {
	deadline := time.Now().Add(within)
	for !proc.IsLeader() {
		if time.Now().After(deadline) {
			return fmt.Errorf("processor did not become leader within %s (another processor bound to schema? use -external-processor)", within)
		}
		if err := sleepCtx(ctx, 50*time.Millisecond); err != nil {
			return err
		}
	}
	return nil
}

// runLevel measures one worker count: warmup → drain → measured window → drain.
func runLevel(ctx context.Context, pool *pgxpool.Pool, metrics *obs.Metrics, o options, gen *workload, workers int) (levelResult, error) {
	res := levelResult{Workers: workers, Statuses: map[string]int64{}}

	if o.warmup > 0 {
		fmt.Fprintf(os.Stderr, "[workers=%d] warmup %s\n", workers, o.warmup)
		if _, err := insertFor(ctx, pool, o, gen, workers, o.warmup, nil); err != nil {
			return res, err
		}
		if _, _, err := waitDrained(ctx, pool, o.drainTimeout, workers, "warmup drain"); err != nil {
			return res, err
		}
	}

	var startID int64
	if err := pool.QueryRow(ctx, selectMaxID).Scan(&startID); err != nil {
		return res, fmt.Errorf("read max id: %w", err)
	}
	busy0 := loopBusySeconds(metrics)

	fmt.Fprintf(os.Stderr, "[workers=%d] measuring %s\n", workers, o.duration)
	windowStart := time.Now()
	stats, err := insertFor(ctx, pool, o, gen, workers, o.duration, func(elapsed time.Duration, ops int64, rate float64) {
		var pending int64
		if err := pool.QueryRow(ctx, selectPending).Scan(&pending); err != nil {
			return
		}
		fmt.Fprintf(os.Stderr, "[workers=%d] t=%2.0fs inserted=%d (%.0f ops/s) pending=%d\n",
			workers, elapsed.Seconds(), ops, rate, pending)
	})
	if err != nil {
		return res, err
	}
	window := time.Since(windowStart)

	var backlog int64
	if err := pool.QueryRow(ctx, selectPending).Scan(&backlog); err != nil {
		return res, fmt.Errorf("read backlog: %w", err)
	}
	var endID int64
	if err := pool.QueryRow(ctx, selectMaxID).Scan(&endID); err != nil {
		return res, fmt.Errorf("read max id: %w", err)
	}

	drainDur, drained, err := waitDrained(ctx, pool, o.drainTimeout, workers, "drain")
	if err != nil {
		return res, err
	}
	// The leader flushes its busy time after the drain returns empty, which is a
	// hair after the sampler saw pending=0; give it a moment before reading ρ.
	if metrics != nil {
		if err := sleepCtx(ctx, 200*time.Millisecond); err != nil {
			return res, err
		}
	}
	busy1 := loopBusySeconds(metrics)

	res.Ops = stats.ops
	res.Registrations = stats.regs
	res.InsertErrors = stats.errs
	res.InsertOpsPerS = float64(stats.ops) / window.Seconds()
	res.InsertRegPerS = float64(stats.regs) / window.Seconds()
	res.InsertP50Ms, res.InsertP95Ms, res.InsertP99Ms = percentilesMs(stats.latencies)
	res.LeaderOpsPerS = float64(stats.ops-min(backlog, stats.ops)) / window.Seconds()
	res.BacklogAtEnd = backlog
	res.DrainSeconds = drainDur.Seconds()
	res.Drained = drained
	res.SustainedOpsPerS = float64(stats.ops) / (window + drainDur).Seconds()
	if metrics != nil {
		rho := (busy1 - busy0) / (window + drainDur).Seconds()
		res.Rho = &rho
	}

	if err := readLatency(ctx, pool, startID, endID, &res); err != nil {
		return res, err
	}
	if err := readStatuses(ctx, pool, startID, endID, &res); err != nil {
		return res, err
	}
	return res, nil
}

// insertStats is what the closed-loop inserters counted during one phase.
type insertStats struct {
	ops, regs, errs int64
	latencies       []time.Duration // one per committed registration
}

// insertFor runs n closed-loop inserters for d, calling progress once a second
// (if non-nil), and returns the merged counters. Errors from a transaction that
// was cut by the phase ending are not counted.
func insertFor(ctx context.Context, pool *pgxpool.Pool, o options, gen *workload, n int, d time.Duration,
	progress func(elapsed time.Duration, ops int64, rate float64),
) (insertStats, error) {
	phaseCtx, cancel := context.WithTimeout(ctx, d)
	defer cancel()

	var (
		ops, regs, errs atomic.Int64
		mu              sync.Mutex
		lat             []time.Duration
		wg              sync.WaitGroup
	)
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func(seed int64) {
			defer wg.Done()
			rng := rand.New(rand.NewSource(seed))
			local := make([]time.Duration, 0, 1024)
			for phaseCtx.Err() == nil {
				req := gen.next(rng)
				t0 := time.Now()
				err := insertOnce(phaseCtx, pool, req)
				if err != nil {
					if phaseCtx.Err() == nil {
						errs.Add(1)
						fmt.Fprintf(os.Stderr, "bench: insert: %v\n", err)
					}
					continue
				}
				local = append(local, time.Since(t0))
				regs.Add(1)
				ops.Add(int64(len(req.Operations)))
			}
			mu.Lock()
			lat = append(lat, local...)
			mu.Unlock()
		}(time.Now().UnixNano() + int64(i))
	}

	start := time.Now()
	if progress != nil {
		t := time.NewTicker(time.Second)
		defer t.Stop()
		var prev int64
	loop:
		for {
			select {
			case <-phaseCtx.Done():
				break loop
			case <-t.C:
				cur := ops.Load()
				progress(time.Since(start), cur, float64(cur-prev))
				prev = cur
			}
		}
	}
	wg.Wait()
	if ctx.Err() != nil {
		return insertStats{}, ctx.Err()
	}
	return insertStats{ops: ops.Load(), regs: regs.Load(), errs: errs.Load(), latencies: lat}, nil
}

// insertOnce is one host transaction as the api node does it: BEGIN, register,
// COMMIT — the shape ADR-0008 advises (insert last, commit immediately).
func insertOnce(ctx context.Context, pool *pgxpool.Pool, req ledger.InsertRequest) error {
	tx, err := pool.Begin(ctx)
	if err != nil {
		return err
	}
	if _, err := ledger.Insert(ctx, tx, req); err != nil {
		_ = tx.Rollback(ctx)
		return err
	}
	return tx.Commit(ctx)
}

// waitDrained polls the PENDING count until it reaches zero or the timeout
// elapses, returning how long the leader took and whether it finished.
func waitDrained(ctx context.Context, pool *pgxpool.Pool, timeout time.Duration, workers int, what string) (time.Duration, bool, error) {
	start := time.Now()
	lastLog := start
	for {
		var pending int64
		if err := pool.QueryRow(ctx, selectPending).Scan(&pending); err != nil {
			return 0, false, fmt.Errorf("read pending: %w", err)
		}
		if pending == 0 {
			return time.Since(start), true, nil
		}
		if time.Since(start) > timeout {
			fmt.Fprintf(os.Stderr, "[workers=%d] %s: gave up after %s with %d still pending\n", workers, what, timeout, pending)
			return time.Since(start), false, nil
		}
		if time.Since(lastLog) >= time.Second {
			fmt.Fprintf(os.Stderr, "[workers=%d] %s: %d pending\n", workers, what, pending)
			lastLog = time.Now()
		}
		if err := sleepCtx(ctx, 20*time.Millisecond); err != nil {
			return 0, false, err
		}
	}
}

// readLatency fills the end-to-end percentiles for the ids of one window.
func readLatency(ctx context.Context, pool *pgxpool.Pool, startID, endID int64, res *levelResult) error {
	var (
		n                 int64
		p50, p95, p99, mx *float64
	)
	if err := pool.QueryRow(ctx, selectLatency, startID, endID).Scan(&n, &p50, &p95, &p99, &mx); err != nil {
		return fmt.Errorf("read latency: %w", err)
	}
	if n == 0 {
		return nil
	}
	res.E2EP50Ms, res.E2EP95Ms, res.E2EP99Ms, res.E2EMaxMs = secMs(p50), secMs(p95), secMs(p99), secMs(mx)
	return nil
}

func secMs(p *float64) float64 {
	if p == nil {
		return 0
	}
	return *p * 1000
}

// readStatuses tallies the terminal statuses of one window's operations — the
// proof that the workload was decided, not merely inserted.
func readStatuses(ctx context.Context, pool *pgxpool.Pool, startID, endID int64, res *levelResult) error {
	rows, err := pool.Query(ctx, selectStatuses, startID, endID)
	if err != nil {
		return fmt.Errorf("read statuses: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var status string
		var n int64
		if err := rows.Scan(&status, &n); err != nil {
			return fmt.Errorf("scan status: %w", err)
		}
		res.Statuses[status] = n
	}
	return rows.Err()
}

// loopBusySeconds reads the leader's cumulative busy time (spec §13 ρ numerator)
// from the in-process registry; 0 when there is no in-process leader.
func loopBusySeconds(m *obs.Metrics) float64 {
	if m == nil {
		return 0
	}
	families, err := m.Registry().Gather()
	if err != nil {
		return 0
	}
	for _, mf := range families {
		if mf.GetName() != "balancedb_loop_busy_seconds_total" {
			continue
		}
		for _, metric := range mf.GetMetric() {
			return metric.GetCounter().GetValue()
		}
	}
	return 0
}

// percentilesMs sorts the client-observed commit latencies and returns p50/p95/p99.
func percentilesMs(lat []time.Duration) (p50, p95, p99 float64) {
	if len(lat) == 0 {
		return 0, 0, 0
	}
	sort.Slice(lat, func(i, j int) bool { return lat[i] < lat[j] })
	at := func(q float64) float64 {
		i := int(math.Ceil(q*float64(len(lat)))) - 1
		i = max(0, min(i, len(lat)-1))
		return float64(lat[i]) / float64(time.Millisecond)
	}
	return at(0.50), at(0.95), at(0.99)
}

// workload builds registrations: -group-size legs over -accounts accounts, small
// positive amounts, effective_at now or spread over the last -backdate-days days.
type workload struct {
	owner     int64
	accounts  int
	groupSize int
	backdate  time.Duration
}

func newWorkload(o options) *workload {
	return &workload{
		owner:     o.owner,
		accounts:  o.accounts,
		groupSize: o.groupSize,
		backdate:  time.Duration(o.backdateDays) * 24 * time.Hour,
	}
}

func (w *workload) next(rng *rand.Rand) ledger.InsertRequest {
	ops := make([]ledger.InsertOp, w.groupSize)
	for i := range ops {
		at := time.Now().UTC()
		if w.backdate > 0 {
			at = at.Add(-time.Duration(rng.Int63n(int64(w.backdate))))
		}
		ops[i] = ledger.InsertOp{
			OwnerID:     w.owner,
			ExternalID:  accountName(rng.Intn(w.accounts)),
			Amount:      int64(rng.Intn(100) + 1),
			EffectiveAt: at,
		}
	}
	return ledger.InsertRequest{IdempotencyKey: newUUID(), Operations: ops}
}

// newUUID returns a random v4 UUID for the required idempotency key. crypto/rand,
// no dependency.
func newUUID() string {
	var b [16]byte
	_, _ = cryptorand.Read(b[:])
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

func printHeader(o options, rep report) {
	shape := "singles"
	if o.groupSize > 1 {
		shape = fmt.Sprintf("groups of %d", o.groupSize)
	}
	when := "now"
	if o.backdateDays > 0 {
		when = fmt.Sprintf("spread over the last %d days", o.backdateDays)
	}
	leader := "in-process"
	if o.external {
		leader = "external"
	}
	fmt.Printf("BalanceDB throughput benchmark\n")
	fmt.Printf("postgres %s, schema %s, leader %s\n", rep.PostgresVersion, rep.Schema, leader)
	fmt.Printf("config: batch_size=%d loop_interval_ms=%d lease_ttl_ms=%d\n", rep.BatchSize, rep.LoopIntervalMs, rep.LeaseTTLMs)
	fmt.Printf("workload: %s, %d accounts, effective_at %s, owner %d\n", shape, o.accounts, when, o.owner)
	fmt.Printf("per level: warmup %s, measured window %s, then drain\n\n", o.warmup, o.duration)
	fmt.Printf("%7s | %12s | %14s | %12s | %11s | %8s | %15s | %14s | %5s\n",
		"workers", "insert ops/s", "insert p50/p99", "leader ops/s", "backlog@end", "drain s", "sustained ops/s", "e2e p50/p99 ms", "rho")
	fmt.Printf("%s\n", strings.Repeat("-", 124))
}

func printRow(r levelResult) {
	rho := "  n/a"
	if r.Rho != nil {
		rho = fmt.Sprintf("%5.2f", *r.Rho)
	}
	drain := fmt.Sprintf("%8.2f", r.DrainSeconds)
	if !r.Drained {
		drain = fmt.Sprintf("%7.0f!", r.DrainSeconds)
	}
	fmt.Printf("%7d | %12.1f | %6.1f /%6.1f | %12.1f | %11d | %s | %15.1f | %6.0f /%6.0f | %s\n",
		r.Workers, r.InsertOpsPerS, r.InsertP50Ms, r.InsertP99Ms, r.LeaderOpsPerS, r.BacklogAtEnd, drain,
		r.SustainedOpsPerS, r.E2EP50Ms, r.E2EP99Ms, rho)
}

func printFooter(rep report) {
	best := 0.0
	for _, l := range rep.Levels {
		best = math.Max(best, l.SustainedOpsPerS)
	}
	fmt.Println()
	if rep.GroupSize > 1 {
		fmt.Printf("peak sustained: %.0f ops/s = %.0f groups/s (group size %d)\n", best, best/float64(rep.GroupSize), rep.GroupSize)
	} else {
		fmt.Printf("peak sustained: %.0f ops/s\n", best)
	}
	for _, l := range rep.Levels {
		extras := []string{}
		for status, n := range l.Statuses {
			if status != "CONFIRMED" {
				extras = append(extras, fmt.Sprintf("%s=%d", status, n))
			}
		}
		if l.InsertErrors > 0 {
			extras = append(extras, fmt.Sprintf("insert_errors=%d", l.InsertErrors))
		}
		if !l.Drained {
			extras = append(extras, "drain timed out (! above)")
		}
		if len(extras) > 0 {
			sort.Strings(extras)
			fmt.Printf("workers=%d: %s\n", l.Workers, strings.Join(extras, ", "))
		}
	}
	fmt.Println("columns: insert = what the inserters committed; leader = decided while inserts ran; sustained = ops / (window + drain);")
	fmt.Println("         e2e = registered_at -> confirmed_at on the DB clock; rho = leader busy time / (window + drain), 1.0 = saturated.")
}

func writeJSON(path string, rep report) error {
	b, err := json.MarshalIndent(rep, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

// dropSchema removes a generated schema on its own short-lived connection.
func dropSchema(ctx context.Context, url, schema string) error {
	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		return err
	}
	defer pool.Close()
	_, err = pool.Exec(ctx, "DROP SCHEMA IF EXISTS "+pgx.Identifier{schema}.Sanitize()+" CASCADE")
	return err
}

func sleepCtx(ctx context.Context, d time.Duration) error {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-t.C:
		return nil
	}
}
